config/routes.rb
Rails.application.routes.draw do
  get 'more_info', to: 'people#more'
  resources :people do
    resources :goods
    resources :pays
    resources :delivers
  end
  devise_for :users
  root to: 'people#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :goods, dependent: :destroy
  has_many :pays, dependent: :destroy
  has_many :delivers, dependent: :destroy
  after_commit :invo_sub
  private
  def invo_sub
    invo_sub = 0
    invo_tax = 0
    invo_total = 0
    invo_profit = 0
    invo_margin = 0
    invo_delv = 0
    invo_dis = 0
    invo_fee = 0
    self.goods.each do |itm|
      invo_sub += itm.qnt * itm.price
    end
    invo_sub
    self.update_columns(subtotal: invo_sub)
    invo_tax = invo_sub * 10.25 / 100
    self.update_columns(tax: invo_tax)
    self.delivers.each do |delv|
      invo_delv += delv.delivery
      invo_dis += delv.discount
      invo_fee += delv.fee
    end
    invo_delv
    self.update_columns(delivery_fee: invo_delv)
    invo_dis
    self.update_columns(discount: invo_dis)
    invo_fee
    self.update_columns(fee: invo_fee)
    invo_total = invo_sub + invo_tax + invo_delv + invo_fee - invo_dis
    self.update_columns(total: invo_total)
    invo_profit = invo_total - self.cost
    self.update_columns(profit: invo_profit)
    invo_margin = (invo_profit / invo_sub * 100).round(2)
    self.update_columns(margin: invo_margin)
  end

  # after_create :inv_itms, :inv_tax, :inv_total, :inv_profit, :inv_per
  #
  # private
  #   def inv_itms
  #     inv_itms = 0
  #     self.goods.each do |itm|
  #       inv_itms += itm.qunt * itm.price
  #     end
  #     inv_itms
  #     self.update(subtotal: inv_itms)
  #   end
  #   def inv_tax
  #      inv_tax = self.subtotal * 10.25 / 100
  #     self.update(tax: inv_tax)
  #   end
  #   def inv_total
  #     inv_total = self.subtotal + self.tax
  #     self.update(total: inv_total )
  #   end
  #   def inv_profit
  #     inv_profit = self.subtotal - self.cost
  #     self.update(profit: inv_profit)
  #   end
  #   def inv_per
  #     inv_per = (self.profit / self.subtotal * 100).round(2)
  #
  #   end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def more
    @people = Person.all
    @goods = Good.all
    @pays = Pay.all
    @delivers = Deliver.all
  end
  def index
    @people = Person.all.order("created_at DESC")
    @goods = Good.all
    @pays = Pay.all
    @delivers = Deliver.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    respond_to do |format|
    format.html
      format.pdf do
        pdf = InvoicePdf.new(@person, view_context)
        send_data pdf.render, filename: "invoice_#{@person.phone}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /people/new
  def new
    @person = current_user.people.build
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = current_user.people.build(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :phone, :email, :address, :address2, :city,
      :state, :zip, :finance, :subtotal, :tax, :total, :user_id, :sale_rep, :cost)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
  def sub_totls
    sub_totls = 0
    @person.goods.each do |comt|
      sub_totls += comt.qnt * comt.price
    end
    sub_totls
  end
  def tax_calc
    tax_calc = sub_totls * 10.25 / 100
  end
  def tot_pay
    tot_pay = 0
    @person.pays.each do |pay|
      tot_pay += pay.amount
    end
    tot_pay
  end
  def inv_dicount
    inv_dicount = 0
    @person.delivers.each do |delv|
      inv_dicount += delv.discount
    end
     inv_dicount ||= "00.00"
  end
  def inv_delivery
    inv_delivery = 0
    @person.delivers.each do |delv|
      inv_delivery += delv.delivery
    end
    inv_delivery ||= "00.00"
  end
  def inv_fee
      inv_fee = 0
    @person.delivers.each do |delv|
       inv_fee = delv.fee
    end
    inv_fee
  end
  def totall
    totll = tax_calc + sub_totls + inv_fee + inv_delivery - inv_dicount
  end
  def tot
    tot = 0
    tot = (totall - tot_pay).round(2)
  end
  def total_invoices
    totals = 0
    Person.all.each do |per|
     totals += per.total
    end
    totals
  end
  def total_subs
    total_subs = 0
    Person.all.each do |per|
     total_subs += per.subtotal
    end
    total_subs
  end
  def total_taxs
    total_taxs = 0
    Person.all.each do |per|
     total_taxs += per.tax
    end
    total_taxs
  end
  def total_costs
    total_costs = 0
    Person.all.each do |per|
     total_costs += per.cost
    end
    total_costs
  end
  def total_delvs
    total_delvs = 0
    Person.all.each do |per|
     total_delvs += per.delivery_fee
    end
    total_delvs
  end
  def total_profits
    total_profits = 0
    Person.all.each do |per|
     total_profits += per.profit
    end
    total_profits
  end
end

app/views/people/_delivery.html.erb
<a href="#" id="show_delivery">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>2- Click to Add Delivery Details!</h3></button>
</a><br>
<div id="delivery" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.delivers.build] do |f| %>
      <div class="row">
        <div class="col">
          <div class="col-sm">
            Delivery Fee: <%= f.text_field :delivery %>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Fee If Applay: <%= f.text_field :fee%>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Discoint If Applay: <%= f.text_field :discount %>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Delivery Date<%= f.date_select :delivery_date %>
          </div>
        </div>
      </div>
      <div class="col-sm"><br>
        <div class="actions">
          <button class="btn btn-success btn-lg btn-block " type="submit"><h3>Click here to ADD Delivery  Details and Discount if Applay!</h3></button>
        </div><br>
      </div>
    <% end %>
  </div><br>
</div><br><br>

app/views/people/_else_details.html.erb
<div class="container" style= 'background-color: #F0FFFF'><br>
  <div class="row">
    <div class="col-sm">
      <p>
        <strong>Name:</strong>
        <%= @person.name.titleize %>
      </p>
      <p>
        <strong>Phone:</strong>
        <%= @person.phone %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @person.email %>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <strong>Address:</strong>
        <%= @person.address.titleize %>
      </p>
      <p>
        <strong>Address2:</strong>
        <%= @person.address2.titleize %>
      </p>
      <p>
        <strong>City:</strong>
        <%= @person.city.titleize %>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <strong>State:</strong>
        <%= @person.state.capitalize %>
      </p>
      <p>
        <strong>Zip:</strong>
        <%= @person.zip %>
      </p>
      <p>
        <strong>Sale Rep:</strong>
        <%= @person.sale_rep.capitalize %>
      </p>
    </div>
  </div><br>
  <div class="container" style="width: 93%">
  <button type="button" class="btn btn-warning btn-lg btn-block">Item Purchase Details!</button>
  </div>

  <center>
    <table class='table table-hover table-striped' style="width: 90%;">
      <thead class='table-dark'>
        <tr>
          <th>QNTY</th>
          <th>Item</th>
          <th>Price</th>
          <th>Description</th>
          <th>Subtotal</th>
          <th>Tax</th>
          <th>Total</th>
          <% if current_user  && current_user.admin? %>
            <th>Action</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <%  %>
        <% @person.goods.each do |itm| %>
          <tr>
            <td><%= itm.qnt %></td>
            <td><%= number_to_currency itm.price %></td>
            <td><%= itm.item %></td>
            <td><%= itm.description %></td>
            <% sub_totl = itm.price * itm.qnt %>
            <td><%= number_to_currency sub_totl %></td>
            <% tax_itm = itm.price * itm.qnt * 10.25 / 100%>
            <td><%= number_to_currency tax_itm %></td>
            <td><%= number_to_currency sub_totl + tax_itm  %></td>
            <% if current_user  && current_user.admin? %>
              <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, itm], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
            <% end %>
          </tr>
        <% end %>
    </table><hr><br>
  </center>
  <div class="container">
    <div class="row">
      <div class="col">
        <button type="button" class="btn btn-success btn-lg btn-block">Delivery Details</button><br>
        <center>
          <% @person.delivers.each do |delv| %>
            Delivert Fee: <%= delv.delivery %><br>
            Fee: <%= delv.fee %><br>
            Discount: <%= delv.discount %><br>
            Delivery Date: <%= delv.delivery_date %><br>
            <% if current_user  && current_user.admin? %>
              <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, delv], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
            <% end %>
          <% end %>
        </center>
      </div>
      <div class="col">
        <font size="4" color="red"><%= number_to_currency sub_totls %> Invoice Subtotal</font><br>
        <font size="4" color="red"><%= number_to_currency tax_calc %> Invoice TAX</font><br>
        <font size="4" color="red"><%= number_to_currency inv_delivery  %> Delivery Fee</font><br>
        <font size="4" color="red"><%= number_to_currency inv_fee %> Fee If Apply  -</font><br>
        <hr>

        <font size="4" color="blue"><%= number_to_currency inv_dicount  %> Discount If Apply</font><br>
        <hr>
        <center>
          <font size="6" color="green"> <%= number_to_currency totall  %> Paid in Full ACEMA </font>
        </center><br>
      </div>
    </div>
  </div>

</div><br>

app/views/people/_false_details.html.erb
<div class="container" style= 'background-color: #F0FFFF'><br>
  <div class="row">
    <div class="col-sm">
      <p>
        <strong>Name:</strong>
        <%= @person.name.titleize %>
      </p>
      <p>
        <strong>Phone:</strong>
        <%= @person.phone %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @person.email %>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <strong>Address:</strong>
        <%= @person.address.titleize %>
      </p>
      <p>
        <strong>Address2:</strong>
        <%= @person.address2.titleize %>
      </p>
      <p>
        <strong>City:</strong>
        <%= @person.city.titleize %>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <strong>State:</strong>
        <%= @person.state.capitalize %>
      </p>
      <p>
        <strong>Zip:</strong>
        <%= @person.zip %>
      </p>
      <p>
        <strong>Sale Rep:</strong>
        <%= @person.sale_rep.capitalize %>
      </p>
    </div>
  </div><br>
  <div class="container" style="width: 93%">
  <button type="button" class="btn btn-warning btn-lg btn-block">Item Purchase Details!</button>
  </div>
    <center>
      <table class='table table-hover table-striped' style="width: 90%;">
        <thead class='table-dark'>
          <tr>
            <th>QNTY</th>
            <th>Item</th>
            <th>Price</th>
            <th>Description</th>
            <th>Subtotal</th>
            <th>Tax</th>
            <th>Total</th
            <% if current_user  && current_user.admin? %>
              <th>Action</th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <%  %>
          <% @person.goods.each do |itm| %>
            <tr>
              <td><%= itm.qnt %></td>
              <td><%= number_to_currency itm.price %></td>
              <td><%= itm.item %></td>
              <td><%= itm.description %></td>
              <% sub_totl = itm.price * itm.qnt %>
              <td><%= number_to_currency sub_totl %></td>
              <% tax_itm = itm.price * itm.qnt * 10.25 / 100%>
              <td><%= number_to_currency tax_itm %></td>
              <td><%= number_to_currency sub_totl + tax_itm  %></td>
              <% if current_user  && current_user.admin? %>
                <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, itm], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table><hr><br>
    </center>

<div class="container">
  <div class="row">
    <div class="col-sm">
    <button type="button" class="btn btn-success btn-lg btn-block">Payments Details</button><br>
      <center>
        <% @person.pays.each do |pay| %>
          <font size="3" color="green"> payment method</font> &nbsp;&nbsp;<%= pay.method %>
          <%= number_to_currency pay.amount %> &nbsp;&nbsp;<br>
          <% if current_user  && current_user.admin? %>
            <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, pay], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
          <% end %>
        <% end %>
      </center>
      <hr>
      <font size="5" color="green"><%= number_to_currency tot_pay %> Total Payments</font>

    </div>
    <div class="col-sm">
      <button type="button" class="btn btn-success btn-lg btn-block">Delivery Details</button><br>
      <center>
        <% @person.delivers.each do |delv| %>
          Delivert Fee: <%= delv.delivery %><br>
          Fee: <%= delv.fee %><br>
          Discount: <%= delv.discount %><br>
          Delivery Date: <%= delv.delivery_date %><br>
          <% if current_user  && current_user.admin? %>
            <td><%= link_to (image_tag('delx.png',  height: '40px', width: '40px')), [@person, delv], method: :delete, data: { confirm: 'You are about delete this item!' } %></td>
          <% end %>
          <hr>
        <% end %>
      </center>
    </div>
    <div class="col-sm">
      <font size="4" color="red"><%= number_to_currency sub_totls %> Items Subtotal</font><br>
      <font size="4" color="red"><%= number_to_currency tax_calc %> Invoice TAX</font><br>
      <font size="4" color="red"><%= number_to_currency inv_delivery %> Delivery Fee</font><br>
      <font size="4" color="red"><%= number_to_currency inv_fee   %> Fee If Apply  -</font><br>
      <font size="4" color="blue"><%= number_to_currency inv_dicount  %> Discount If Apply</font><br>
      <hr>
      <font size="5" color="red"><%= number_to_currency totall %> Invoice Due!</font><br>
      <font size="5" color="green"><%= number_to_currency tot_pay %> Total Payments</font><br>
      <hr>
      <center>
        <font size="6" color="red"><%= number_to_currency tot %><br> Invoice Remaining</font>
      </center>

    </div>
  </div>
</div><br>
</div><br>

<a href="#" id="show_items">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>1- Click to Add Items Details!</h3></button><br>
</a>
<div id="items" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.goods.build] do |f| %>
      <div class="container">
              <div class="row">
                <div class="col-sm">
                <%= f.label :item %>
                  <%= f.select :item, [ 'SELECT ITEM','BedRomm', 'Sofa', ['Loveseat'], ['Chair']] %>
                </div>
                <div class="col-sm">
                  <%= f.label :qnt %><br>
                  <%= f.select :qnt, [0,1,2,3,4,5,6,7,8,9,10,11,12] %>
                </div>
                <div class="col-sm">
                  <%= f.label :description %>
                  <%= f.text_field :description %>
                </div>
                <div class="col-sm">
                  <%= f.label :price %>
                  <%= f.text_field :price %>
                </div>
                <div class="col-sm">
                <%= f.label :vendor %><br>
                  <%= f.select:vendor, [ 'SELECT VENDOR','Titanic', 'United', ['Coaster'], ['Other']] %>
                </div>
                <div class="col-sm">
                <%= f.label :cost %>
                  <%= f.text_field :cost %>
                </div>
                <div class="col-sm"><br>
                  <div class="actions">
                    <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD New Item!</h3></button>
                  </div><br>
                </div>
              </div>
            </div>
    <% end %>
  </div><br>
</div><br>

<a href="#" id="show_delivery">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>2- Click to Add Delivery Details!</h3></button>
</a><br>
<div id="delivery" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.delivers.build] do |f| %>
      <div class="row">
        <div class="col">
          <div class="col-sm">
            Delivery Fee: <%= f.text_field :delivery %>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Fee If Applay: <%= f.text_field :fee%>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Discoint If Applay: <%= f.text_field :discount %>
          </div>
        </div>
        <div class="col">
          <div class="col-sm">
            Delivery Date<%= f.date_select :delivery_date %>
          </div>
        </div>
      </div>
      <div class="col-sm"><br>
        <div class="actions">
          <button class="btn btn-success btn-lg btn-block " type="submit"><h3>Click here to ADD Delivery  Details and Discount if Applay!</h3></button>
        </div><br>
      </div>
    <% end %>
  </div><br>
</div><br><br>

<a href="#" id="show_pays">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>3- Click to Add Payment Details!</h3></button><br>
</a>
<div id="pays" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.pays.build] do |f| %>
      <div class="row">
        <div class="col">
          <div class="col-sm">
          <%= f.label :amount %>
          <%= f.text_field :amount%>
        </div>
          </div>
          <div class="col">
          <div class="col-sm">
            <%= f.label :method %>
            <%= f.text_field :method %>
          </div>
          </div>
        </div>
      <div class="col-sm"><br>
        <div class="actions">
          <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD Payment!</h3></button>
        </div><br>
      </div>
    <% end %>
  </div><br>
</div><br>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container" style="background-color: #cceeff;" >
    <div class="row">
      <div class="col-sm">
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name, class:'form-control' %>
        </div>

        <div class="field">
          <%= form.label :phone %>
          <%= form.text_field :phone, class:'form-control' %>
        </div>

        <div class="field">
          <%= form.label :email %>
          <%= form.text_field :email, class:'form-control' %>
        </div>
      </div>
      <div class="col-sm">
        <div class="field">
          <%= form.label :address %>
          <%= form.text_field :address, class:'form-control'%>
        </div>

        <div class="field">
          <%= form.label :address2 %>
          <%= form.text_field :address2, class:'form-control' %>
        </div>

        <div class="field">
          <%= form.label :city %>
          <%= form.text_field :city, class:'form-control' %>
        </div>
      </div>
      <div class="col-sm">
        <div class="field">
          <%= form.label :state %>
          <%= form.text_field :state, class:'form-control' %>
        </div>

        <div class="field">
          <%= form.label :zip %>
          <%= form.text_field :zip, class:'form-control' %>
        </div><br>

        <div class="field">
          <%= form.select :sale_rep,[current_user.username] %>
        </div>
      </div>
    </div><br>
</div><br>
  <button type="button" class="btn btn-danger btn-lg btn-block">
    Please Click this if sale by Finance! <%= form.check_box :finance %>
  </button><br>

  <% if current_user  && current_user.admin? %>
    <div class="field">
      <font size="5" color="red">Please Update the Actual Cost for this Invoice!</font><br>
      <%= form.text_field :cost, class:'form-control' %>
    </div><br>
  <% end %>

  <div class="actions">
    <button class="btn btn-info btn-lg btn-block" type="submit"><h2>Proceed to Step #2 to Add Sales Details! </h2></button>
  </div>
<% end %>

app/views/people/_items.html.erb
<a href="#" id="show_items">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>1- Click to Add Items Details!</h3></button><br>
</a>
<div id="items" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.goods.build] do |f| %>
      <div class="container">
              <div class="row">
                <div class="col-sm">
                <%= f.label :item %>
                  <%= f.select :item, [ 'SELECT ITEM','BedRomm', 'Sofa', ['Loveseat'], ['Chair']] %>
                </div>
                <div class="col-sm">
                  <%= f.label :qnt %><br>
                  <%= f.select :qnt, [0,1,2,3,4,5,6,7,8,9,10,11,12] %>
                </div>
                <div class="col-sm">
                  <%= f.label :description %>
                  <%= f.text_field :description %>
                </div>
                <div class="col-sm">
                  <%= f.label :price %>
                  <%= f.text_field :price %>
                </div>
                <div class="col-sm">
                <%= f.label :vendor %><br>
                  <%= f.select:vendor, [ 'SELECT VENDOR','Titanic', 'United', ['Coaster'], ['Other']] %>
                </div>
                <div class="col-sm">
                <%= f.label :cost %>
                  <%= f.text_field :cost %>
                </div>
                <div class="col-sm"><br>
                  <div class="actions">
                    <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD New Item!</h3></button>
                  </div><br>
                </div>
              </div>
            </div>
    <% end %>
  </div><br>
</div><br>

app/views/people/_pay.html.erb
<a href="#" id="show_pays">
  <button type="button" class="btn btn-info btn-lg btn-block"><h3>3- Click to Add Payment Details!</h3></button><br>
</a>
<div id="pays" class="hidden">
  <div class="container" style= 'background-color: #F0FFFF'><br>
    <%= form_for [@person, @person.pays.build] do |f| %>
      <div class="row">
        <div class="col">
          <div class="col-sm">
          <%= f.label :amount %>
          <%= f.text_field :amount%>
        </div>
          </div>
          <div class="col">
          <div class="col-sm">
            <%= f.label :method %>
            <%= f.text_field :method %>
          </div>
          </div>
        </div>
      <div class="col-sm"><br>
        <div class="actions">
          <button class="btn btn-success btn-lg btn-block " type="submit"><h3> Click here to ADD Payment!</h3></button>
        </div><br>
      </div>
    <% end %>
  </div><br>
</div><br>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person, :class => "btn btn-danger" %>
<%= link_to 'Back to All Invoices!', people_path, :class => "btn btn-outline-success"  %>

app/views/people/index.html.erb
<button type="button" class="btn btn-success btn-lg btn-block"><h2>All Invoices Table  </h2></button>

<center>
  <div class="container"><br>
    <table id="per" class="table table-striped table-bordered" style="width: 80%;">
      <thead class="table-success">
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Date</th>
          <% if current_user  && current_user.admin? %>
            <th>Action</th>
            <th>Action</th>
            <th>Action</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @people.each do |person| %>
          <tr>
            <td><%= link_to person.name.titleize, person %></td>
            <td><%= person.phone %></td>
            <td><%= person.created_at.strftime("%m/%d/%Y")%></td>
            <% if current_user  && current_user.admin? %>
              <td><%= link_to 'Show', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</center>

<br>
<%= link_to ' Create New Invoice Click Here Please!', new_person_path, :class => "btn btn-outline-danger btn-lg btn-block"%>

app/views/people/new.html.erb
<button type="button" class="btn btn-info btn-lg btn-block">
<h1>Start New Invoice Step #1</h1>
  </button><br>

<%= render 'form', person: @person %>

<%= link_to 'Back to All Invoices!', people_path, :class => "btn btn-outline-success" %>

app/views/people/show.html.erb
<% if current_user  && current_user.admin? %>
  <div class='container'>
  <table class='table table-hover table-striped'>
    <thead class='table-dark'>
      <tr>
        <th>Total Invoce</th>
        <th>Sub Total</th>
        <th>Tax</th>
        <th>Discount</th>
        <th>Delivery</th>
        <th>Fee</th>
        <th>Cost</th>
        <th>Profit</th>
        <th>Margin</th>
      </tr>
    </thead>

    <tbody>
        <tr>
          <td><%= number_to_currency @person.total %></td>
            <td><%= number_to_currency @person.subtotal %></td>
            <td><%= number_to_currency @person.tax %></td>
            <td><%= number_to_currency @person.discount %></td>
            <td><%= number_to_currency @person.delivery_fee %></td>
            <td><%= number_to_currency @person.fee %></td>
            <td><%= number_to_currency @person.cost %></td>
            <td><%= number_to_currency   prof = @person.subtotal - @person.cost  %></td>
            <td><%= ( prof / @person.subtotal * 100).round(2) %> %</td>
        </tr>
    </tbody>
  </table>
</div>
<% end %>
<%= link_to "print Recipt (PDF)", person_path(@person, format: 'pdf'), class:"btn btn-outline-success" %><br><br>
<% if @person.finance == false %>
<button type="button" class="btn btn-danger btn-lg btn-block">
  <h3>Payment need Attention</h3>
</button><br>
  <button type="button" class="btn btn-primary btn-lg btn-block">Purchase Details for <%= @person.name.titleize  %></button>
  <%= render 'false_details' %>
<% else %>
  <button type="button" class="btn btn-success btn-lg btn-block"><h3>
    Finance Purchase  Paid in Full&nbsp;&nbsp; <%= number_to_currency @person.total  %></h3>
  </button><br>
  <button type="button" class="btn btn-primary btn-lg btn-block">Purchase Details for <%= @person.name.titleize  %></button>
  <%= render 'else_details' %>
  <%= render 'items' %>
  <%= render 'delivery' %>

<% end %>

<br>
<% if current_user  && current_user.admin? %>
  <%= link_to 'Edit Customer Information Only!', edit_person_path(@person), :class => "btn btn-danger"  %>
<% end %>
<%= link_to 'Back to All Invoices!', people_path, :class => "btn btn-outline-success"  %>