config/routes.rb
Rails.application.routes.draw do
  get 'more_info', to: 'people#more'
  resources :people do
    resources :goods
    resources :pays
    resources :delivers
  end
  devise_for :users
  root to: 'people#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #99ccff;">
<%= link_to 'DR CONCEPT' , people_path, :class => "btn btn-primary"%>&nbsp;&nbsp;
  <form class="form-inline my-2 my-lg-0">
    <% if current_user  && current_user.admin? %>
      <%= link_to 'Owner', more_info_path, :class => "btn btn-outline-primary"%>&nbsp;&nbsp;
    <% end %>
    <% if user_signed_in? %>
      <button type="button" class="btn btn-primary">
        Rep Name <span class="badge badge-light"><%= current_user.username %></span>
        <span class="sr-only">unread messages</span>
      </button>&nbsp;&nbsp;

      <%= link_to 'Edit profile', edit_user_registration_path, :class => "btn btn-outline-primary"%>&nbsp;&nbsp;

      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-outline-primary"  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-outline-primary"  %>&nbsp;&nbsp;
      <%= link_to "Login", new_user_session_path, :class => "btn btn-outline-primary" %>
    <% end %>
    </form>
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <div class="container">
      <%= render 'layouts/nav' %><br>
      <%= yield %>
    </div>
  </body>
</html>